/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import datos.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import visor.fasegrupos;
import visor.imagenes;
import visor.mascota;

/**
 *
 * @author USUARIO
 */
public class CrudMundial extends javax.swing.JFrame {
 
    
    /**
     * Creates new form CrudMundial
     */
    public CrudMundial() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crud = new javax.swing.JPanel();
        Id = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        Pais = new javax.swing.JLabel();
        Region = new javax.swing.JLabel();
        Capitan = new javax.swing.JLabel();
        Mundiales = new javax.swing.JLabel();
        txtpais = new javax.swing.JTextField();
        txtregion = new javax.swing.JTextField();
        txtcapitan = new javax.swing.JTextField();
        txtranking = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmundial = new javax.swing.JTable();
        Ranking = new javax.swing.JLabel();
        txtmundiales = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crud.setBackground(new java.awt.Color(153, 0, 0));
        crud.setForeground(new java.awt.Color(0, 0, 0));

        Id.setBackground(new java.awt.Color(153, 153, 255));
        Id.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 255, 255));
        Id.setText("ID");

        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 0));

        Pais.setBackground(new java.awt.Color(153, 153, 255));
        Pais.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        Pais.setForeground(new java.awt.Color(255, 255, 255));
        Pais.setText("PAIS");

        Region.setBackground(new java.awt.Color(153, 153, 255));
        Region.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        Region.setForeground(new java.awt.Color(255, 255, 255));
        Region.setText("REGION");

        Capitan.setBackground(new java.awt.Color(153, 153, 255));
        Capitan.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        Capitan.setForeground(new java.awt.Color(255, 255, 255));
        Capitan.setText("CAPITAN");

        Mundiales.setBackground(new java.awt.Color(153, 153, 255));
        Mundiales.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        Mundiales.setForeground(new java.awt.Color(255, 255, 255));
        Mundiales.setText("MUNDIALES");

        txtpais.setBackground(new java.awt.Color(255, 255, 255));
        txtpais.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        txtpais.setForeground(new java.awt.Color(0, 0, 0));
        txtpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaisActionPerformed(evt);
            }
        });

        txtregion.setBackground(new java.awt.Color(255, 255, 255));
        txtregion.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        txtregion.setForeground(new java.awt.Color(0, 0, 0));
        txtregion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregionActionPerformed(evt);
            }
        });

        txtcapitan.setBackground(new java.awt.Color(255, 255, 255));
        txtcapitan.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        txtcapitan.setForeground(new java.awt.Color(0, 0, 0));
        txtcapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcapitanActionPerformed(evt);
            }
        });

        txtranking.setBackground(new java.awt.Color(255, 255, 255));
        txtranking.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        txtranking.setForeground(new java.awt.Color(0, 0, 0));
        txtranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrankingActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(102, 0, 0));
        btnguardar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("GUARDAR");
        btnguardar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setBackground(new java.awt.Color(102, 0, 0));
        btnmodificar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar.setText("MODIFICAR");
        btnmodificar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(102, 0, 0));
        btneliminar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("ELIMINAR");
        btneliminar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setBackground(new java.awt.Color(102, 0, 0));
        btnlimpiar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        tblmundial.setBackground(new java.awt.Color(51, 0, 0));
        tblmundial.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        tblmundial.setForeground(new java.awt.Color(255, 255, 255));
        tblmundial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Pais", "Region", "Capitan", "Ranking", "Mundiales_Ganados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblmundial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmundialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmundial);

        Ranking.setBackground(new java.awt.Color(153, 153, 255));
        Ranking.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        Ranking.setForeground(new java.awt.Color(255, 255, 255));
        Ranking.setText("RANKING");

        txtmundiales.setBackground(new java.awt.Color(255, 255, 255));
        txtmundiales.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        txtmundiales.setForeground(new java.awt.Color(0, 0, 0));
        txtmundiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmundialesActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mundial.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo fifa.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camara.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIFA WORLD CUP QATAR 2022");

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("FASE GRUPOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crudLayout = new javax.swing.GroupLayout(crud);
        crud.setLayout(crudLayout);
        crudLayout.setHorizontalGroup(
            crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
            .addGroup(crudLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crudLayout.createSequentialGroup()
                .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(crudLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crudLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(crudLayout.createSequentialGroup()
                                        .addComponent(Region)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtregion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Capitan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crudLayout.createSequentialGroup()
                                        .addComponent(Id)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(Pais)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(crudLayout.createSequentialGroup()
                                .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(crudLayout.createSequentialGroup()
                                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19))
                                    .addComponent(Ranking))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnmodificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtranking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mundiales)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crudLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(crudLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmundiales, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crudLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btnlimpiar))))))
                    .addGroup(crudLayout.createSequentialGroup()
                        .addContainerGap(59, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(31, 31, 31))
        );
        crudLayout.setVerticalGroup(
            crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudLayout.createSequentialGroup()
                .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(crudLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pais)
                            .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Capitan)
                                .addComponent(txtcapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Region)
                                .addComponent(txtregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ranking)
                            .addComponent(txtranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mundiales)
                            .addComponent(txtmundiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(crudLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton1)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(crud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(crud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        String ID= txtid.getText();
        String PAIS= txtpais.getText();
        String REGION= txtregion.getText();
        String CAPITAN= txtcapitan.getText();
        String RANKING= txtranking.getText();
        String MUNDIALES= txtmundiales.getText();
        try {
            Connection con = Conexion.getConnection();
            PreparedStatement ps= con.prepareStatement("INSERT INTO jugadores(Pais, Region, Capitan, Ranking,Mundiales_Ganados) VALUES(?, ?, ?, ?,?)");

            ps.setString(1, PAIS);
            ps.setString(2, REGION);
            ps.setString(3, CAPITAN);
            ps.setString(4, RANKING);
            ps.setString(5,MUNDIALES );
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"SE GUARDO EL REGISTRO");
            limpiar();
            cargarTabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.toString());
        }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:

        int ID= Integer.parseInt(txtid.getText());
        String PAIS= txtpais.getText();
        String REGION= txtregion.getText();
        String CAPITAN= txtcapitan.getText();
        String RANKING= txtranking.getText();
        String MUNDIALES = txtmundiales.getText();
        try {
            Connection con = Conexion.getConnection();
            PreparedStatement ps= con.prepareStatement("UPDATE jugadores SET Pais=?, Region=?, Capitan=?, Ranking=?,Mundiales_Ganados=? WHERE Id = ?");

            ps.setString(1, PAIS);
            ps.setString(2, REGION);
            ps.setString(3, CAPITAN);
            ps.setString(4, RANKING);
            ps.setString(5, MUNDIALES);
            ps.setInt(6,ID);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"SE MODIFICO EL REGISTRO");
            limpiar();
            cargarTabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        String Id= txtid.getText();

        try {
            Connection con = Conexion.getConnection();
            PreparedStatement ps= con.prepareStatement("DELETE FROM jugadores WHERE Id=?");

            ps.setString(1, Id);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"SE ELIMINO EL REGISTRO CUATE");
            limpiar();
            cargarTabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtcapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcapitanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcapitanActionPerformed

    private void txtrankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrankingActionPerformed

    private void txtpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaisActionPerformed

    private void txtregionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregionActionPerformed

    private void tblmundialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmundialMouseClicked
        // TODO add your handling code here:
        try {
            int fila = tblmundial.getSelectedRow();
            int Id= Integer.parseInt(tblmundial.getValueAt(fila,0).toString());
            PreparedStatement ps;
            ResultSet rs;
            Connection con = Conexion.getConnection();
            ps= con.prepareStatement("SELECT  Pais, Region, Capitan, Ranking,Mundiales_Ganados FROM jugadores WHERE Id=?");

            ps.setInt(1,Id);
            rs = ps.executeQuery();

            while(rs.next()){
                txtid.setText(String.valueOf(Id));
                txtpais.setText(rs.getString("PAIS"));
                txtregion.setText(rs.getString("REGION"));
                txtcapitan.setText(rs.getString("CAPITAN"));
                txtranking.setText(rs.getString("RANKING"));
                txtmundiales.setText(rs.getString("MUNDIALES_GANADOS"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_tblmundialMouseClicked
public void limpiar(){
        txtid.setText("");
          txtpais.setText("");
            txtregion.setText("");
              txtcapitan.setText("");
                txtranking.setText("");
                txtmundiales.setText("");
    }
private void cargarTabla(){
        DefaultTableModel modeloTabla= (DefaultTableModel) tblmundial.getModel();
        modeloTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        try {
            Connection con = Conexion.getConnection();
             ps= con.prepareStatement("SELECT Id, Pais, Region, Capitan, Ranking,Mundiales_Ganados FROM jugadores");
         
            rs= ps.executeQuery();
            rsmd= rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int indice =0; indice<columnas; indice++){
                    fila[indice]= rs.getObject(indice+1);
                }
                modeloTabla.addRow(fila);
            }
            
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e.toString());
        }
        
    }
    private void txtmundialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmundialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmundialesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           imagenes abrir = new imagenes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         fasegrupos abrir = new fasegrupos();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          MENU abrir = new MENU();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudMundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudMundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudMundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudMundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudMundial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Capitan;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Mundiales;
    private javax.swing.JLabel Pais;
    private javax.swing.JLabel Ranking;
    private javax.swing.JLabel Region;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JPanel crud;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmundial;
    private javax.swing.JTextField txtcapitan;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmundiales;
    private javax.swing.JTextField txtpais;
    private javax.swing.JTextField txtranking;
    private javax.swing.JTextField txtregion;
    // End of variables declaration//GEN-END:variables
}
